name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
  cypress-tests-desktop:
    needs: eslint
    runs-on: ubuntu-latest
    container: cypress/browsers
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run end-to-end tests on desktop viewport 🧪
        uses: cypress-io/github-action@v2
        with:
          command: npm run
